name: Build local_rcc

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        run: choco install ninja

      - name: Configure CMake
        run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        run: cmake --build build --target local_rcc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: local-rcc-dll
          path: build/local_rcc.dll
